version: "3.3"
services:
    database:
        build:
            context: .
            dockerfile: database.Dockerfile
        volumes:
            - "dbdata:/var/lib/postgresql/data"
        networks:
            - node_backend_boilerplate
        ports:
            - 5432:5432
    app:
        depends_on:
            - database
        build:
            context: .
            dockerfile: app.Dockerfile
        networks:
            - node_backend_boilerplate
        ports:
            - 3000:3000
volumes:
    dbdata:
networks:
    node_backend_boilerplate:
